/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModesIndexRouteImport } from './routes/modes/index'
import { Route as LayoutsIndexRouteImport } from './routes/layouts/index'
import { Route as ModesKeybykeyIndexRouteImport } from './routes/modes/keybykey/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesIndexRoute = ModesIndexRouteImport.update({
  id: '/modes/',
  path: '/modes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsIndexRoute = LayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesKeybykeyIndexRoute = ModesKeybykeyIndexRouteImport.update({
  id: '/modes/keybykey/',
  path: '/modes/keybykey/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layouts/': typeof LayoutsIndexRoute
  '/modes/': typeof ModesIndexRoute
  '/modes/keybykey/': typeof ModesKeybykeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layouts': typeof LayoutsIndexRoute
  '/modes': typeof ModesIndexRoute
  '/modes/keybykey': typeof ModesKeybykeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layouts/': typeof LayoutsIndexRoute
  '/modes/': typeof ModesIndexRoute
  '/modes/keybykey/': typeof ModesKeybykeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/layouts/' | '/modes/' | '/modes/keybykey/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/layouts' | '/modes' | '/modes/keybykey'
  id: '__root__' | '/' | '/layouts/' | '/modes/' | '/modes/keybykey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutsIndexRoute: typeof LayoutsIndexRoute
  ModesIndexRoute: typeof ModesIndexRoute
  ModesKeybykeyIndexRoute: typeof ModesKeybykeyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/': {
      id: '/modes/'
      path: '/modes'
      fullPath: '/modes/'
      preLoaderRoute: typeof ModesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts/': {
      id: '/layouts/'
      path: '/layouts'
      fullPath: '/layouts/'
      preLoaderRoute: typeof LayoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/keybykey/': {
      id: '/modes/keybykey/'
      path: '/modes/keybykey'
      fullPath: '/modes/keybykey/'
      preLoaderRoute: typeof ModesKeybykeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutsIndexRoute: LayoutsIndexRoute,
  ModesIndexRoute: ModesIndexRoute,
  ModesKeybykeyIndexRoute: ModesKeybykeyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
